# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: analysis.proto
# Protobuf Python Version: 6.33.5
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    33,
    5,
    '',
    'analysis.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0e\x61nalysis.proto\x12\x08\x61nalysis\"\x80\x01\n\x14\x45mailAnalysisRequest\x12\x10\n\x08\x65mail_id\x18\x01 \x01(\t\x12\x0e\n\x06sender\x18\x02 \x01(\t\x12\x0f\n\x07subject\x18\x03 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x04 \x01(\t\x12\x0c\n\x04urls\x18\x05 \x03(\t\x12\x16\n\x0ehas_attachment\x18\x06 \x01(\x08\"R\n\x15\x45mailAnalysisResponse\x12\r\n\x05score\x18\x01 \x01(\x05\x12\x12\n\nrisk_level\x18\x02 \x01(\t\x12\x16\n\x0ejustifications\x18\x03 \x03(\t2b\n\x0f\x41nalysisService\x12O\n\x0c\x41nalyzeEmail\x12\x1e.analysis.EmailAnalysisRequest\x1a\x1f.analysis.EmailAnalysisResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'analysis_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EMAILANALYSISREQUEST']._serialized_start=29
  _globals['_EMAILANALYSISREQUEST']._serialized_end=157
  _globals['_EMAILANALYSISRESPONSE']._serialized_start=159
  _globals['_EMAILANALYSISRESPONSE']._serialized_end=241
  _globals['_ANALYSISSERVICE']._serialized_start=243
  _globals['_ANALYSISSERVICE']._serialized_end=341
# @@protoc_insertion_point(module_scope)
